---
- name: Gather fact 'kernel'
  ansible.builtin.setup:
    filter: "kernel"
- name: "Check kernel version is {{ kernel_version_comparison_operator + ' ' + kernel_version_expected | string }}"
  ansible.builtin.fail:
    msg: "{{ ansible_facts.kernel }} is not {{ kernel_version_comparison_operator + ' ' + kernel_version_expected | string }}"
  when: ansible_facts.kernel is not version(kernel_version_expected, operator=kernel_version_comparison_operator)
