---
chrony_max_stratum: 9
chrony_max_system_clock_deviation: 0.005
# NOTE: Usually in OSISM deployments ceph is one of the most time sensitive
# applications. In its default ceph starts to show warnings when it
# detects clock drift above 0.05 seconds between monitors [1]. Therefore,
# to ensure the quality of NTP time allows to keep the drift between two
# systems to less or equal to 0.05 seconds a default of 0.025 seconds will
# be used for `chrony_max_upper_clock_error_bound`.
#
# [1]: https://docs.ceph.com/en/latest/rados/configuration/mon-config-ref/#confval-mon_clock_drift_allowed
chrony_max_upper_clock_error_bound: "{{ chrony_max_system_clock_deviation + 0.02 }}"
