---
- project:
    merge-mode: squash-merge
    check:
      jobs:
        - yamllint
        - ansible-lint
    gate:
      jobs:
        - yamllint
        - ansible-lint
    periodic-daily:
      jobs:
        - yamllint
        - ansible-lint
