---
- secret:
    name: SECRET_ANSIBLE_COLLECTION_VALIDATIONS
    data:
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - Ld6KvXJqMY1aJHMdTGO1OCWmSTOR38cMaRtWbtb0hgM14E9uSJGsMa+qLSrBwFtCHFGlY
          On1Ne9G+ggrz7tE7S6qO2KpVy5iOutufMYhzs6gWQ0jtNZqsPGWoc3fO9y3qZfv8Ilyif
          tn/yjY7qMr+XORk+2h5jWUOMbj4Sw91YTHTIQ9WeeD6FEPTTtlHZaNIsX9rZMcAnCjXd1
          NkcdhJSI2iYfK9nlBbg8zgz/LKUOZsHLxdZus3mI1gDwXnpPFfbH1Bpt3Lb5Zf0X31HH2
          XqayiVBxtItCWt1sXZU/bh6S1YmlJuUS/jWtod2MQWdLvnyzJ/XVVlP+lXh0NgYJXekhx
          bMET8d02yx8U+p6H+BjD2gTyD+ICklNSQk4g8H8zrdWA88J7xLAgx620607mPdIQ9SeEg
          51E1v/nIOeQprHwynsupLENY2Kjhesyn3gLBRpZdlV/uJ5k/ybuypUUEo8hxHGpqMsK86
          BOKYW90gjI8LeFBf4KjtbaSP8KGIddHZl4zoJjx8aRulRxnJnwVtZIS02ankWWTkzjBNo
          yBt1wx7RB/Rl6PecDHiNSqDqgXlnCXx1XkC+h74HvvgBGouACQA8OfgrQFQ37iehThXq4
          ePu2k20zRxzd+v626jQUCGW/0Iyuu+jzn/96tTSbSHk5s5uPqz1F82hUjW9ACo=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - rNjvVJIPlgb/yOC4A3RjN33TCy2ruvQSyD0jafEGMliwf3fIz5MTvv+p9+j3GlDD/Izk7
          oA1jSPAxqbEynftXxGLVhEGm60ZoK7X3RGi7AA50A7/l81uZaFRVdNToTubV348RSbPKd
          +PYY+Pp31imZWVmEf2y0x1GP1Xjap307FHpvsWD1bb2g/bit6yRsyAq038ZNKwXBAbEjO
          QI1FZDYxsnwHS1QIvU/q5RcQgCM75ep6krfXK89WOl4rxTfPNaP4EhUF35NbLCUoI2Cor
          C8CNYlsd9su4phOizWkAEQaZkVSWLKc64iuH+4YHhqn5XYP3EjxFu/Wu88P1HmDng+iaT
          K/33V0RaTJgbhJOIbK8wQGhKe6JdcuIRyejxtwV51pPumHRwPF6gxNtXLc7/+QaTbtjm6
          47N45B2wmP3LEU950DzMw6HJWDt7BV4S9q4VUsN4CSi7bcpMW2qpLZa2IASw1YGD/EFP8
          xyeqxXw2lvO9YU6P4EngkPtiJAWpnvFS50Y5VOzgDG9eb1lDs28CfXD1leBV4tau7tBrd
          F+KtklGE65/fXCI3PhGJfd5eFuy8qv9mcotF+whkr3PzPtKTjNA1E5aglZtCT60ARenlz
          bT0rGMwTWIrcn1mZkr5uZ6NpPZ1hNb8dmQTSwr/5pXWdvzvJO4zYxdcGsWgAMw=

- job:
    name: ansible-collection-validations-container-image-osism-ansible-push
    parent: abstract-container-image-osism-ansible-push
    secrets:
      - name: secret
        secret: SECRET_ANSIBLE_COLLECTION_VALIDATIONS
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - yamllint
        - ansible-lint
    gate:
      jobs:
        - yamllint
        - ansible-lint
    periodic-daily:
      jobs:
        - yamllint
        - ansible-lint
    post:
      jobs:
        - ansible-collection-validations-container-image-osism-ansible-push:
            branches: main
