---
- project:
    check:
      jobs:
        - build-sphinx-docs
        - yamllint
        - ansible-lint
    gate:
      jobs:
        - build-sphinx-docs
        - yamllint
        - ansible-lint
