---
- secret:
    name: SECRET_ANSIBLE_COLLECTION_VALIDATIONS
    data:
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - CjhQX4TI0WhueHLHX3YMNesb/OapiFX4NrLrNX7t1c/x6ChaMPLRS9wac6wVOfb6EBlXH
          72IYLXDk1tWm5RGZzc9GMt0fC62X9OKxjPCdIhui/aR0GOh2HjuX1wAqjmO1Gn2WmiXcd
          qLP9QtqLPxJ7rXk0XNLyykHpXu44g2KEzasYxOraKXekACtumCHJqSS+3kKuSdNfHj02B
          BtCdqfdQg6IYomrBCwrddlc+uuhZti1FwdI4CMPD2Y4YNp365pa8yQlPE5o3JJ0SAR0V3
          sgxqKQgpls0eaU66UuHXxm3sF+ijHUrMGPlqyH4p2Lf2MENN7dg7Hd4rgyG/5QGZdH+kG
          rTEW28dJ6IkMWqGyIZIJQWcANmoyYOd5xvCFmhXJUVsJ4BOnrUWxoW5HmPsUZkVxE1UfH
          7oJHRXIFI2Gf77/0m/ByzJqLgceV1zvjsxpbubYIsHrN7A3dvzUI+226I7ZKacQBpC9dw
          LJrZHIM+KHwrRd/c+++j69wDC+cePuxud/MFCQuNDBc6Ys/HA07M6GqejFhdkJeY8NwfN
          0HLPFr2XJeZkfyBkSISTg3plP0zA98zcWn/bDAUPYCaUCL2Azmu4h/yMUxqlS5UTlHuAr
          rNfqfSGvQZOE3unhN4PUOUq6klAMIL3NjYtyMcE2TMbMcVEv+KUPVirS44JKwU=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - Vq/4W0+Mk9q/f+rCCsG/FUmLY0pEVwCsKqmWSOsH8Mnkmza023KATbY+U80wOZ0jDSjUx
          AHNKRe0eDT5oRBTYTCUS13eA1pVCFaFHS9K6WdO+sQszPYfjbiz9eupLPZUwuHwf1Xurk
          k91Hc/4/9Ju7ItqWOkYynPEFeE6Vjvm9BUCByB6IIz98R0IhbvrTj/1Wg9h82nJoRAXU7
          2X29XGX+/sUIKnqdlnDoWQDN+/A5pSZtphz69wBh5/OL8uKmRU2Lw+C9l4OOsIJvZGJwR
          QxBeNLF3o57KClVIaTOuZLUOihb1/hOXgeKAJW8kL3RlMhUuE6EXC5JiK2aAd1MAcbeNy
          a/oiYPZl+HvufTuVRKzNZTPrt8yMxr9FH1fDSxvuS4VVpnFyiHPhz6eQMdvTPACkgV/7T
          HSgqopPvn916FmbwBjB8sNY0ioZijcYqwAYeHbR0heKWTZPO8GLfGKCwTQGtBJL1HgCUy
          eso9CHYcs2gTZSuQhSarqhiaN334OihVRDRTHu+AibOY1QkCq0Gk/c8inrmMa56OMi83s
          c+1GeJTvaG1HsvH58cNA8b7OYWGrfGdNjhbBD6ociAJzFliol9iYQFDgTbdnK1T02JfAF
          +A11guDd447JnDnxn1iMKwaMuaeROKEhUxJFopUlbyfmY8jf+aJna5OdjHTtw8=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - edWrcnJowWe+5vbNt1ZyZoSIuV3FqvNZ4oRrhJ5LB20oHhCa/isqRsWTy1PoAtouHg+Zm
          tnashG+Lcxbddpm+3qZY8zloWfHqmiB+a5rPkAX/2lSAKwZ6CMMMFiTXoyV87eoZrBvW2
          j22R4boUg9Am/PcUGL4EnzG2RQ04oXErvgytFWcWC9sbKNMFvV3RNASXke0ZxoJZTQVA2
          Cngjt88/I5idRtdaa7JjenYOz7vGryAVQ9+fE/WaJDUhLm7Rr+n9lgjujDchkmLN1SULS
          Mt+kE03BQUqbQVsJV4XSNwJAafuc/RBqgGP4GazstXggt5tTkNk9WoWwU/gUOV/DR/AEJ
          M00AiUwDXxWXzS6VStjZIIjfeFDLN15jAw/oiYoNwAqcXLm6NL9T2J3D0ybrkoMiNin80
          kx7rCcrywEBWy/aV5WGrTIw2YkwWiHL3E9W1i5GkkeixxpZHwRNB3V1DvS8iy3u9W1mPd
          vAE+Ee0e8pJ0Ucw0R2HVKuCcA8LBWzE1NJgSP5oEPzx+1mlJTKkmKY4Sux3DeVOW4gVZQ
          Fn0uXaiYsaRhj0wqhEF+3O1bWj2cPD1l6W+pIj8VyS384g+UCiLSJKp3QgayDiEeBWxjN
          5+GacANYJRYozvGZhmGkJk1GPNMLnNqFYBR+4bnJJrFLPWaNzvFyngDDf0Qqrw=

- job:
    name: ansible-collection-validations-container-image-osism-ansible-push
    parent: abstract-container-image-osism-ansible-push
    secrets:
      - name: secret
        secret: SECRET_ANSIBLE_COLLECTION_VALIDATIONS
        pass-to-parent: true

- job:
    name: abstract-ansible-collection-validations-molecule
    parent: ansible-molecule
    abstract: true
    nodeset:
      nodes:
        - name: centos-9-stream
          label: centos-9-stream
        - name: debian-bookworm
          label: debian-bookworm
        - name: ubuntu-jammy
          label: ubuntu-jammy
        - name: ubuntu-noble
          label: ubuntu-noble
    vars:
      ansible_molecule_ansible_version: "11.6.0"
    files:
      - '^\.zuul\.yaml$'
      - '^molecule\/delegated\/[^\/]*yml$'
      - '^molecule\/requirements\.txt$'

- job:
    name: ansible-collection-validations-molecule-container_status
    parent: abstract-ansible-collection-validations-molecule
    vars:
      ansible_role: container_status
    files:
      - '^roles\/container_status\/.*$'
      - '^molecule\/delegated\/[a-zA-Z0-9_-]+\/container_status.*$'

- job:
    name: ansible-collection-validations-molecule-docker_version
    parent: abstract-ansible-collection-validations-molecule
    vars:
      ansible_role: docker_version
    files:
      - '^roles\/docker_version\/.*$'
      - '^molecule\/delegated\/[a-zA-Z0-9_-]+\/docker_version.*$'

- job:
    name: ansible-collection-validations-molecule-kernel_version
    parent: abstract-ansible-collection-validations-molecule
    vars:
      ansible_role: kernel_version
    files:
      - '^roles\/kernel_version\/.*$'
      - '^molecule\/delegated\/[a-zA-Z0-9_-]+\/kernel_version.*$'

- job:
    name: ansible-collection-validations-molecule-mysql_open_files_limit
    parent: abstract-ansible-collection-validations-molecule
    vars:
      ansible_role: mysql_open_files_limit
    files:
      - '^roles\/mysql_open_files_limit\/.*$'
      - '^molecule\/delegated\/[a-zA-Z0-9_-]+\/mysql_open_files_limit.*$'

- job:
    name: ansible-collection-validations-molecule-stress
    parent: abstract-ansible-collection-validations-molecule
    vars:
      ansible_role: stress
    files:
      - '^roles\/stress\/.*$'
      - '^molecule\/delegated\/[a-zA-Z0-9_-]+\/stress.*$'

- job:
    name: ansible-collection-validations-molecule-system_encoding
    parent: abstract-ansible-collection-validations-molecule
    vars:
      ansible_role: system_encoding
    files:
      - '^roles\/system_encoding\/.*$'
      - '^molecule\/delegated\/[a-zA-Z0-9_-]+\/system_encoding.*$'

- job:
    name: ansible-collection-validations-molecule-ulimits
    parent: abstract-ansible-collection-validations-molecule
    vars:
      ansible_role: ulimits
    files:
      - '^roles\/ulimits\/.*$'
      - '^molecule\/delegated\/[a-zA-Z0-9_-]+\/ulimits.*$'

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - ansible-collection-validations-molecule-container_status
        - ansible-collection-validations-molecule-docker_version
        - ansible-collection-validations-molecule-kernel_version
        - ansible-collection-validations-molecule-mysql_open_files_limit
        - ansible-collection-validations-molecule-stress
        - ansible-collection-validations-molecule-system_encoding
        - ansible-collection-validations-molecule-ulimits
        - ansible-collection-ensure-readme
        - ansible-lint
        - flake8
        - python-black
        - yamllint
    gate:
      jobs:
        - ansible-collection-validations-molecule-container_status
        - ansible-collection-validations-molecule-docker_version
        - ansible-collection-validations-molecule-kernel_version
        - ansible-collection-validations-molecule-mysql_open_files_limit
        - ansible-collection-validations-molecule-stress
        - ansible-collection-validations-molecule-system_encoding
        - ansible-collection-validations-molecule-ulimits
        - ansible-collection-ensure-readme
        - ansible-lint
        - flake8
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - python-black
        - yamllint
    post:
      jobs:
        - ansible-collection-validations-container-image-osism-ansible-push:
            branches: main
