---
namespace: osism
name: validations
version: 999.0.0
readme: README.md
authors:
  - OSISM community <info@osism.tech>
description: OSISM validations roles
license_file: LICENSE
tags:
  - osism
  - system
  - cloud
  - infrastructure
dependencies: {}
repository: https://github.com/osism/ansible-collection-validations.git
documentation: https://osism.github.io/docs/intro/
homepage: https://osism.tech
issues: https://github.com/osism/ansible-collection-validations/issues
