---
- name: Check prometheus is ready and healthy
  ansible.builtin.uri:
    <<: &prometheus_auth
      force_basic_auth: true
      url_username: "{{ prometheus_alert_status_user }}"
      url_password: "{{ prometheus_alert_status_password }}"
    method: HEAD
    url: "{{ prometheus_alert_status_endpoint }}/-/{{ item }}"
    status_code:
      - 200
  loop:
    - ready
    - healthy

- name: Get alerts from prometheus
  ansible.builtin.uri:
    <<: *prometheus_auth
    headers:
      Content-Type: application/json
    method: GET
    url: "{{ prometheus_alert_status_endpoint }}/api/v1/alerts"
    status_code:
      - 200
  register: _alerts

- name: Assert successful alert retrieval
  ansible.builtin.assert:
    that:
      - _alerts.json.status == 'success'

- name: Filter alert list
  ansible.builtin.set_fact:
    _alerts_filtered: "{{
      _alerts_filtered | default(_alerts.json.data.alerts)
                       | selectattr('labels.' + item.label, 'defined')
                       | rejectattr('labels.' + item.label, 'in', item.filter)
                       | union(_alerts_filtered | default(_alerts.json.data.alerts)
                                                | selectattr('labels.' + item.label, 'undefined'))
  }}"
  loop: "{{ prometheus_alert_status_filter | dict2items(key_name='label', value_name='filter') }}"

- name: Show alerts
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ _alerts_filtered | default(_alerts.json.data.alerts) }}"
  loop_control:
    label: "{{ item.labels }}"

- name: Assert there are no pending or firing alerts
  ansible.builtin.assert:
    that:
      - _alerts_filtered | default(_alerts.json.data.alerts) | length == 0
    success_msg: 'No alerts are pending/firing'
    fail_msg: "There are {{ _alerts_filtered | default(_alerts.json.data.alerts) | length }} alerts pending/firing"
