---
- name: Ensure EPEL repository
  ansible.builtin.include_role:
    name: osism.commons.repository
  when: ansible_os_family == "RedHat"

- name: Ensure docker
  ansible.builtin.include_role:
    name: osism.services.docker
  vars:
    docker_user: zuul
    docker_group: zuul
    docker_python_install: false
    docker_version: "5:26.0.2"
