---
- name: Create refstack workdir
  become: true
  ansible.builtin.file:
    path: "{{ refstack_workdir }}"
    state: directory
    mode: '0750'
    owner: dragon
    group: dragon
  delegate_to: "{{ refstack_manager }}"

- name: Copy tempest.conf file
  ansible.builtin.template:
    src: tempest.conf.j2
    dest: "{{ refstack_workdir }}/tempest.conf"
    owner: dragon
    group: dragon
    mode: '0640'
  delegate_to: "{{ refstack_manager }}"

- name: Copy accounts.yaml file
  ansible.builtin.template:
    src: accounts.yaml.j2
    dest: "{{ refstack_workdir }}/accounts.yaml"
    owner: dragon
    group: dragon
    mode: '0640'
  delegate_to: "{{ refstack_manager }}"

- name: Copy script files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ refstack_workdir }}/{{ item }}"
    owner: dragon
    group: dragon
    mode: '0755'
  loop: "{{ refstack_scripts }}"
  delegate_to: "{{ refstack_manager }}"
