---
# source: https://github.com/openstack/tripleo-validations/blob/master/roles/container_status/tasks/main.yaml

- name: Set container_cli fact from the inventory
  set_fact:
    container_cli: "{{ hostvars[inventory_hostname].container_cli |default('docker', true) }}"

- name: Get failed containers for podman
  changed_when: false
  become: true
  command: >
    {{ container_cli }}
    {% raw %}
    ps -a --filter 'status=exited' --format '{{ .Names }} {{ .Status }}'
    {% endraw %}
  register: failed_containers

- name: Fail if we detect failed containers
  fail:
    msg: "Failed container detected: {{ item }}."
  when: item is not match(".* Exited \(0\) .* ago")
  loop: "{{ failed_containers.stdout_lines }}"
