---
galaxy_info:
  author: Jan Horstmann
  description: Role osism.validations.tempest
  company: OSISM GmbH
  license: Apache License 2.0
  min_ansible_version: 2.13.0
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - osism
    - system
    - openstack
dependencies: []
