---
refstack_bootstrap: true
refstack_install: true

# This is the version used in setup_env of refstack-client
refstack_tempest_version: "29.0.0"

refstack_target: compute
refstack_guideline: "2020.11"

refstack_keystone_endpoint: https://api.testbed.osism.xyz:5000/v3
refstack_workdir: /opt/refstack
refstack_cloud: admin

refstack_admin_users:
  - refstack-4
refstack_users:
  - refstack-0
  - refstack-1
  - refstack-2
  - refstack-3
  - refstack-4

refstack_image_url: https://github.com/cirros-dev/cirros/releases/download/0.6.1/cirros-0.6.1-x86_64-disk.img

refstack_superadmin_password: password
refstack_admin_password: password
refstack_user_password: password

refstack_region: RegionOne

refstack_public_network: public
refstack_network_name: refstack

refstack_manager: testbed-manager

refstack_keypair: refstack
refstack_project: refstack-4

refstack_enable_cinder: true
refstack_enable_glance: true
refstack_enable_heat: true
refstack_enable_neutron: true
refstack_enable_nova: true
refstack_enable_swift: false

refstack_volume_device_name: vdb
refstack_image_ssh_user: cirros

refstack_scripts:
  - prepare.sh
  - run.sh
  - single.sh
  - test.sh
  - upload.sh

refstack_domain: Default
refstack_domain_id: default

refstack_admin: admin
refstack_admin_project: admin
